version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_DATABASE=laravel
      - DB_USERNAME=sail
      - DB_PASSWORD=password

  database:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'sail'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'sail-mysql:/var/lib/mysql'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      - PMA_HOST=database
      - PMA_USER=sail
      - PMA_PASSWORD=password
    depends_on:
      - database

volumes:
  sail-mysql:
    driver: local